//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
// Note: requires additional types generated from: mixed_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHT0115Q01grdCHT0115Request")]
  public partial class CHT0115Q01grdCHT0115Request : global::ProtoBuf.IExtensible
  {
    public CHT0115Q01grdCHT0115Request() {}
    
    private string _susik_detail_gubun = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"susik_detail_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string susik_detail_gubun
    {
      get { return _susik_detail_gubun; }
      set { _susik_detail_gubun = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
