//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ORCATransferOrdersResponse")]
  public partial class ORCATransferOrdersResponse : global::ProtoBuf.IExtensible
  {
    public ORCATransferOrdersResponse() {}
    
    private readonly global::System.Collections.Generic.List<ORCATransferOrdersHeaderInfo> _header_item = new global::System.Collections.Generic.List<ORCATransferOrdersHeaderInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"header_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ORCATransferOrdersHeaderInfo> header_item
    {
      get { return _header_item; }
    }
  
    private readonly global::System.Collections.Generic.List<ORCATransferOrdersHealthInsuranceInfo> _health_ins_item = new global::System.Collections.Generic.List<ORCATransferOrdersHealthInsuranceInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"health_ins_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ORCATransferOrdersHealthInsuranceInfo> health_ins_item
    {
      get { return _health_ins_item; }
    }
  
    private readonly global::System.Collections.Generic.List<ORCATransferOrdersDiseaseInfo> _disease_item = new global::System.Collections.Generic.List<ORCATransferOrdersDiseaseInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"disease_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ORCATransferOrdersDiseaseInfo> disease_item
    {
      get { return _disease_item; }
    }
  
    private readonly global::System.Collections.Generic.List<ORCATransferOrdersClaimInfo> _claim_item = new global::System.Collections.Generic.List<ORCATransferOrdersClaimInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"claim_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ORCATransferOrdersClaimInfo> claim_item
    {
      get { return _claim_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
