//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CFFormUnevenPrescribeLayDRG0120Response")]
  public partial class CFFormUnevenPrescribeLayDRG0120Response : global::ProtoBuf.IExtensible
  {
    public CFFormUnevenPrescribeLayDRG0120Response() {}
    
    private readonly global::System.Collections.Generic.List<CFFormUnevenPrescribeLayDRG0120Info> _lay_drg_item = new global::System.Collections.Generic.List<CFFormUnevenPrescribeLayDRG0120Info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"lay_drg_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CFFormUnevenPrescribeLayDRG0120Info> lay_drg_item
    {
      get { return _lay_drg_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
