//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckHangSangInfoResponse")]
  public partial class CheckHangSangInfoResponse : global::ProtoBuf.IExtensible
  {
    public CheckHangSangInfoResponse() {}
    
    private DataStringListItemInfo _result_check = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataStringListItemInfo result_check
    {
      get { return _result_check; }
      set { _result_check = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
