//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DmlMaxGroupSerRequest")]
  public partial class DmlMaxGroupSerRequest : global::ProtoBuf.IExtensible
  {
    public DmlMaxGroupSerRequest() {}
    
    private string _bunho = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bunho", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bunho
    {
      get { return _bunho; }
      set { _bunho = value; }
    }
    private string _pk_key = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pk_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pk_key
    {
      get { return _pk_key; }
      set { _pk_key = value; }
    }
    private string _input_tab = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"input_tab", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string input_tab
    {
      get { return _input_tab; }
      set { _input_tab = value; }
    }
    private string _max_group_ser = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"max_group_ser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string max_group_ser
    {
      get { return _max_group_ser; }
      set { _max_group_ser = value; }
    }
    private string _key_obj = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"key_obj", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string key_obj
    {
      get { return _key_obj; }
      set { _key_obj = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}