//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FnCplLoadDupGrdHangmogRequest")]
  public partial class FnCplLoadDupGrdHangmogRequest : global::ProtoBuf.IExtensible
  {
    public FnCplLoadDupGrdHangmogRequest() {}
    
    private readonly global::System.Collections.Generic.List<FnCplLoadDupGrdHangmogInfo> _fn_cpl_info = new global::System.Collections.Generic.List<FnCplLoadDupGrdHangmogInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"fn_cpl_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FnCplLoadDupGrdHangmogInfo> fn_cpl_info
    {
      get { return _fn_cpl_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
