//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FnInpLoadJaewonIlsuResponse")]
  public partial class FnInpLoadJaewonIlsuResponse : global::ProtoBuf.IExtensible
  {
    public FnInpLoadJaewonIlsuResponse() {}
    
    private readonly global::System.Collections.Generic.List<FnInpLoadJaewonIlsuInfo> _lsu_item = new global::System.Collections.Generic.List<FnInpLoadJaewonIlsuInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"lsu_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FnInpLoadJaewonIlsuInfo> lsu_item
    {
      get { return _lsu_item; }
    }
  
    private string _retVal = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"retVal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string retVal
    {
      get { return _retVal; }
      set { _retVal = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
