//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetApproveFlagsResponse")]
  public partial class GetApproveFlagsResponse : global::ProtoBuf.IExtensible
  {
    public GetApproveFlagsResponse() {}
    
    private ComboListItemInfo _postapprove_visible_info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"postapprove_visible_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ComboListItemInfo postapprove_visible_info
    {
      get { return _postapprove_visible_info; }
      set { _postapprove_visible_info = value; }
    }
    private ComboListItemInfo _approve_force_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"approve_force_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ComboListItemInfo approve_force_info
    {
      get { return _approve_force_info; }
      set { _approve_force_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
