//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetOutJinryoCommentCntRequest")]
  public partial class GetOutJinryoCommentCntRequest : global::ProtoBuf.IExtensible
  {
    public GetOutJinryoCommentCntRequest() {}
    
    private GetOutJinryoCommentCntInfo _jinryo_comment_cnt_info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"jinryo_comment_cnt_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GetOutJinryoCommentCntInfo jinryo_comment_cnt_info
    {
      get { return _jinryo_comment_cnt_info; }
      set { _jinryo_comment_cnt_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
