//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HIOcsCheckJundalPartLoadJaeryoJundalResponse")]
  public partial class HIOcsCheckJundalPartLoadJaeryoJundalResponse : global::ProtoBuf.IExtensible
  {
    public HIOcsCheckJundalPartLoadJaeryoJundalResponse() {}
    
    private readonly global::System.Collections.Generic.List<HIOcsCheckJundalPartLoadJaeryoJundalInfo> _check_jundal_item = new global::System.Collections.Generic.List<HIOcsCheckJundalPartLoadJaeryoJundalInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"check_jundal_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<HIOcsCheckJundalPartLoadJaeryoJundalInfo> check_jundal_item
    {
      get { return _check_jundal_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
