//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HIOcsSpecificCommentRequest")]
  public partial class HIOcsSpecificCommentRequest : global::ProtoBuf.IExtensible
  {
    public HIOcsSpecificCommentRequest() {}
    
    private string _specific_comment = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"specific_comment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specific_comment
    {
      get { return _specific_comment; }
      set { _specific_comment = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
