//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HIOcsSpecificCommentResponse")]
  public partial class HIOcsSpecificCommentResponse : global::ProtoBuf.IExtensible
  {
    public HIOcsSpecificCommentResponse() {}
    
    private readonly global::System.Collections.Generic.List<HIOcsSpecificCommentInfo> _spec_comment_item = new global::System.Collections.Generic.List<HIOcsSpecificCommentInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"spec_comment_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<HIOcsSpecificCommentInfo> spec_comment_item
    {
      get { return _spec_comment_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
