//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InsteadModifiedCheckResponse")]
  public partial class InsteadModifiedCheckResponse : global::ProtoBuf.IExtensible
  {
    public InsteadModifiedCheckResponse() {}
    
    private string _isPossibleInsteadOrder = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isPossibleInsteadOrder", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string isPossibleInsteadOrder
    {
      get { return _isPossibleInsteadOrder; }
      set { _isPossibleInsteadOrder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
