//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IpwonReserStatusRequest")]
  public partial class IpwonReserStatusRequest : global::ProtoBuf.IExtensible
  {
    public IpwonReserStatusRequest() {}
    
    private IpwonReserStatusInfo _reser_status_info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reser_status_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public IpwonReserStatusInfo reser_status_info
    {
      get { return _reser_status_info; }
      set { _reser_status_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
