//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
// Note: requires additional types generated from: mixed_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IsToiwonGojiYNandEndOrderResponse")]
  public partial class IsToiwonGojiYNandEndOrderResponse : global::ProtoBuf.IExtensible
  {
    public IsToiwonGojiYNandEndOrderResponse() {}
    
    private string _toiwon_goji_yn = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"toiwon_goji_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string toiwon_goji_yn
    {
      get { return _toiwon_goji_yn; }
      set { _toiwon_goji_yn = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
