//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadSearchOrder2Response")]
  public partial class LoadSearchOrder2Response : global::ProtoBuf.IExtensible
  {
    public LoadSearchOrder2Response() {}
    
    private readonly global::System.Collections.Generic.List<LoadSearchOrderInfo> _search_result = new global::System.Collections.Generic.List<LoadSearchOrderInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"search_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LoadSearchOrderInfo> search_result
    {
      get { return _search_result; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
