//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
// Note: requires additional types generated from: mixed_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadColumnCodeNameRequest")]
  public partial class LoadColumnCodeNameRequest : global::ProtoBuf.IExtensible
  {
    public LoadColumnCodeNameRequest() {}
    
    private LoadColumnCodeNameInfo _request_value = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"request_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public LoadColumnCodeNameInfo request_value
    {
      get { return _request_value; }
      set { _request_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
