//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ocs.lib_service.proto
// Note: requires additional types generated from: ocs.lib_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadOftenUsedResponse")]
  public partial class LoadOftenUsedResponse : global::ProtoBuf.IExtensible
  {
    public LoadOftenUsedResponse() {}
    
    private readonly global::System.Collections.Generic.List<LoadOftenUsedResponseInfo> _used_info = new global::System.Collections.Generic.List<LoadOftenUsedResponseInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"used_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LoadOftenUsedResponseInfo> used_info
    {
      get { return _used_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
