//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadOcs0132Response")]
  public partial class LoadOcs0132Response : global::ProtoBuf.IExtensible
  {
    public LoadOcs0132Response() {}
    
    private readonly global::System.Collections.Generic.List<LoadOcs0132Info> _load_ocs0132_info = new global::System.Collections.Generic.List<LoadOcs0132Info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"load_ocs0132_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LoadOcs0132Info> load_ocs0132_info
    {
      get { return _load_ocs0132_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
