//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadOcs0131Response")]
  public partial class LoadOcs0131Response : global::ProtoBuf.IExtensible
  {
    public LoadOcs0131Response() {}
    
    private readonly global::System.Collections.Generic.List<LoadOcs0131Info> _ocs0131_info = new global::System.Collections.Generic.List<LoadOcs0131Info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ocs0131_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LoadOcs0131Info> ocs0131_info
    {
      get { return _ocs0131_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
