//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ocs.lib_service.proto
// Note: requires additional types generated from: ocs.lib_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadOftenUsedRequest")]
  public partial class LoadOftenUsedRequest : global::ProtoBuf.IExtensible
  {
    public LoadOftenUsedRequest() {}
    
    private LoadOftenUsedInfo _input_info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"input_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public LoadOftenUsedInfo input_info
    {
      get { return _input_info; }
      set { _input_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
