//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OBGetJundaTable1Response")]
  public partial class OBGetJundaTable1Response : global::ProtoBuf.IExtensible
  {
    public OBGetJundaTable1Response() {}
    
    private readonly global::System.Collections.Generic.List<OBGetJundaTable1Info> _jundal_table_item = new global::System.Collections.Generic.List<OBGetJundaTable1Info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"jundal_table_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OBGetJundaTable1Info> jundal_table_item
    {
      get { return _jundal_table_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
