//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OBLoadSearchOrderInfoDRGResponse")]
  public partial class OBLoadSearchOrderInfoDRGResponse : global::ProtoBuf.IExtensible
  {
    public OBLoadSearchOrderInfoDRGResponse() {}
    
    private readonly global::System.Collections.Generic.List<OBLoadSearchOrderInfoDRGInfo> _search_order_drg_item = new global::System.Collections.Generic.List<OBLoadSearchOrderInfoDRGInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"search_order_drg_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OBLoadSearchOrderInfoDRGInfo> search_order_drg_item
    {
      get { return _search_order_drg_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
