//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OcsoLoadCht0110Response")]
  public partial class OcsoLoadCht0110Response : global::ProtoBuf.IExtensible
  {
    public OcsoLoadCht0110Response() {}
    
    private readonly global::System.Collections.Generic.List<OcsoLoadCht0110Info> _cht0110_info = new global::System.Collections.Generic.List<OcsoLoadCht0110Info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cht0110_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OcsoLoadCht0110Info> cht0110_info
    {
      get { return _cht0110_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
