//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OcsoOCS1003P01CheckIsSameNameYnRequest")]
  public partial class OcsoOCS1003P01CheckIsSameNameYnRequest : global::ProtoBuf.IExtensible
  {
    public OcsoOCS1003P01CheckIsSameNameYnRequest() {}
    
    private string _naewon_date;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"naewon_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string naewon_date
    {
      get { return _naewon_date; }
      set { _naewon_date = value; }
    }
    private string _gwa;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gwa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gwa
    {
      get { return _gwa; }
      set { _gwa = value; }
    }
    private string _naewon_yn;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"naewon_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string naewon_yn
    {
      get { return _naewon_yn; }
      set { _naewon_yn = value; }
    }
    private string _reser_yn;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"reser_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string reser_yn
    {
      get { return _reser_yn; }
      set { _reser_yn = value; }
    }
    private string _doctor_mode_yn;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"doctor_mode_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string doctor_mode_yn
    {
      get { return _doctor_mode_yn; }
      set { _doctor_mode_yn = value; }
    }
    private string _doctor;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"doctor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string doctor
    {
      get { return _doctor; }
      set { _doctor = value; }
    }
    private string _bunho;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"bunho", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string bunho
    {
      get { return _bunho; }
      set { _bunho = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
