//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OcsoProcHQNInterfaceResponse")]
  public partial class OcsoProcHQNInterfaceResponse : global::ProtoBuf.IExtensible
  {
    public OcsoProcHQNInterfaceResponse() {}
    
    private string _pkphy7401 = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pkphy7401", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pkphy7401
    {
      get { return _pkphy7401; }
      set { _pkphy7401 = value; }
    }
    private string _rtnIfsCnt = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rtnIfsCnt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rtnIfsCnt
    {
      get { return _rtnIfsCnt; }
      set { _rtnIfsCnt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
