//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OcsoProcHQNInterfaceRequest")]
  public partial class OcsoProcHQNInterfaceRequest : global::ProtoBuf.IExtensible
  {
    public OcsoProcHQNInterfaceRequest() {}
    
    private OcsoSelectedPatientInfo _patient_info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"patient_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OcsoSelectedPatientInfo patient_info
    {
      get { return _patient_info; }
      set { _patient_info = value; }
    }
    private string _io_gubun = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"io_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_gubun
    {
      get { return _io_gubun; }
      set { _io_gubun = value; }
    }
    private string _data_dubun = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data_dubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data_dubun
    {
      get { return _data_dubun; }
      set { _data_dubun = value; }
    }
    private string _user_id = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
