//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OcsoGetNotApproveOrderCntResponse")]
  public partial class OcsoGetNotApproveOrderCntResponse : global::ProtoBuf.IExtensible
  {
    public OcsoGetNotApproveOrderCntResponse() {}
    
    private string _approve_order_cnt_result = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"approve_order_cnt_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string approve_order_cnt_result
    {
      get { return _approve_order_cnt_result; }
      set { _approve_order_cnt_result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
