//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OFFormSetMakeFormLoadRequest")]
  public partial class OFFormSetMakeFormLoadRequest : global::ProtoBuf.IExtensible
  {
    public OFFormSetMakeFormLoadRequest() {}
    
    private bool _is_doctor_mode = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"is_doctor_mode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_doctor_mode
    {
      get { return _is_doctor_mode; }
      set { _is_doctor_mode = value; }
    }
    private string _sabun = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sabun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sabun
    {
      get { return _sabun; }
      set { _sabun = value; }
    }
    private string _memb = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"memb", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string memb
    {
      get { return _memb; }
      set { _memb = value; }
    }
    private string _input_tab = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"input_tab", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string input_tab
    {
      get { return _input_tab; }
      set { _input_tab = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
