//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OFUpdateDataResponse")]
  public partial class OFUpdateDataResponse : global::ProtoBuf.IExtensible
  {
    public OFUpdateDataResponse() {}
    
    private bool _update_result_1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"update_result_1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool update_result_1
    {
      get { return _update_result_1; }
      set { _update_result_1 = value; }
    }
    private bool _update_result_2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"update_result_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool update_result_2
    {
      get { return _update_result_2; }
      set { _update_result_2 = value; }
    }
    private bool _update_result_3;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"update_result_3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool update_result_3
    {
      get { return _update_result_3; }
      set { _update_result_3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
