//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PatientInfoLoadPatientNaewonListResponse")]
  public partial class PatientInfoLoadPatientNaewonListResponse : global::ProtoBuf.IExtensible
  {
    public PatientInfoLoadPatientNaewonListResponse() {}
    
    private readonly global::System.Collections.Generic.List<LoadPatientBaseInfo> _patient_base_item = new global::System.Collections.Generic.List<LoadPatientBaseInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"patient_base_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LoadPatientBaseInfo> patient_base_item
    {
      get { return _patient_base_item; }
    }
  
    private readonly global::System.Collections.Generic.List<LoadPatientNaewonListInfo> _patient_naewon_item = new global::System.Collections.Generic.List<LoadPatientNaewonListInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"patient_naewon_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LoadPatientNaewonListInfo> patient_naewon_item
    {
      get { return _patient_naewon_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
