//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: service.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrOcsLoadIpwonReserInfoResponse")]
  public partial class PrOcsLoadIpwonReserInfoResponse : global::ProtoBuf.IExtensible
  {
    public PrOcsLoadIpwonReserInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<PrOcsLoadIpwonReserInfo> _reser_info_item = new global::System.Collections.Generic.List<PrOcsLoadIpwonReserInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"reser_info_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PrOcsLoadIpwonReserInfo> reser_info_item
    {
      get { return _reser_info_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
