//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReservedCommentDloOCS0221Response")]
  public partial class ReservedCommentDloOCS0221Response : global::ProtoBuf.IExtensible
  {
    public ReservedCommentDloOCS0221Response() {}
    
    private readonly global::System.Collections.Generic.List<ReservedCommentDloOCS0221Info> _reserved_cmt_item = new global::System.Collections.Generic.List<ReservedCommentDloOCS0221Info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"reserved_cmt_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ReservedCommentDloOCS0221Info> reserved_cmt_item
    {
      get { return _reserved_cmt_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
