//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: nuro_service.proto
// Note: requires additional types generated from: nuro_model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OUT0101U02ComboListResponse")]
  public partial class OUT0101U02ComboListResponse : global::ProtoBuf.IExtensible
  {
    public OUT0101U02ComboListResponse() {}
    
    private readonly global::System.Collections.Generic.List<ComboListItemInfo> _sex_combo_list_item = new global::System.Collections.Generic.List<ComboListItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"sex_combo_list_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ComboListItemInfo> sex_combo_list_item
    {
      get { return _sex_combo_list_item; }
    }
  
    private readonly global::System.Collections.Generic.List<ComboListItemInfo> _bunho_combo_list_item = new global::System.Collections.Generic.List<ComboListItemInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bunho_combo_list_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ComboListItemInfo> bunho_combo_list_item
    {
      get { return _bunho_combo_list_item; }
    }
  
    private readonly global::System.Collections.Generic.List<ComboListItemInfo> _tel_combo_list_item = new global::System.Collections.Generic.List<ComboListItemInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"tel_combo_list_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ComboListItemInfo> tel_combo_list_item
    {
      get { return _tel_combo_list_item; }
    }
  
    private readonly global::System.Collections.Generic.List<ComboListItemInfo> _bonin_combo_list_item = new global::System.Collections.Generic.List<ComboListItemInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"bonin_combo_list_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ComboListItemInfo> bonin_combo_list_item
    {
      get { return _bonin_combo_list_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
