//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: nuro_service.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RES1001U00ReservationScheduleListGroupedRequest")]
  public partial class RES1001U00ReservationScheduleListGroupedRequest : global::ProtoBuf.IExtensible
  {
    public RES1001U00ReservationScheduleListGroupedRequest() {}
    
    private string _exam_pre_date = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"exam_pre_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string exam_pre_date
    {
      get { return _exam_pre_date; }
      set { _exam_pre_date = value; }
    }
    private string _department_code = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"department_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string department_code
    {
      get { return _department_code; }
      set { _department_code = value; }
    }
    private string _doctor_code = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"doctor_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doctor_code
    {
      get { return _doctor_code; }
      set { _doctor_code = value; }
    }
    private string _from_time_am = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"from_time_am", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string from_time_am
    {
      get { return _from_time_am; }
      set { _from_time_am = value; }
    }
    private string _to_time_am = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"to_time_am", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string to_time_am
    {
      get { return _to_time_am; }
      set { _to_time_am = value; }
    }
    private string _from_time_pm = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"from_time_pm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string from_time_pm
    {
      get { return _from_time_pm; }
      set { _from_time_pm = value; }
    }
    private string _to_time_pm = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"to_time_pm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string to_time_pm
    {
      get { return _to_time_pm; }
      set { _to_time_pm = value; }
    }
    private string _avg_time = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"avg_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string avg_time
    {
      get { return _avg_time; }
      set { _avg_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
