//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: nuro_service.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RES1001U00FrmModifyReserGrdRES1001Request")]
  public partial class RES1001U00FrmModifyReserGrdRES1001Request : global::ProtoBuf.IExtensible
  {
    public RES1001U00FrmModifyReserGrdRES1001Request() {}
    
    private string _doctor;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"doctor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string doctor
    {
      get { return _doctor; }
      set { _doctor = value; }
    }
    private string _day_of_week;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"day_of_week", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string day_of_week
    {
      get { return _day_of_week; }
      set { _day_of_week = value; }
    }
    private string _date;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string date
    {
      get { return _date; }
      set { _date = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
