//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FindPatientForm.proto
namespace IHIS.CloudConnector.Messaging
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"FindPatientFromRequest")]
    public partial class FindPatientFromRequest : global::ProtoBuf.IExtensible
    {
        public FindPatientFromRequest() { }

        private string _patient_name2;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"patient_name2", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string patient_name2
        {
            get { return _patient_name2; }
            set { _patient_name2 = value; }
        }
        private string _sex;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"sex", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string sex
        {
            get { return _sex; }
            set { _sex = value; }
        }
        private string _brith;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"brith", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string brith
        {
            get { return _brith; }
            set { _brith = value; }
        }
        private string _tel;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"tel", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string tel
        {
            get { return _tel; }
            set { _tel = value; }
        }
        private string _patient_code;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"patient_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string patient_code
        {
            get { return _patient_code; }
            set { _patient_code = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
}
