//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XMstGridDeleteRowRequest")]
  public partial class XMstGridDeleteRowRequest : global::ProtoBuf.IExtensible
  {
    public XMstGridDeleteRowRequest() {}
    
    private string _table_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"table_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string table_name
    {
      get { return _table_name; }
      set { _table_name = value; }
    }
    private string _where_cmd = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"where_cmd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string where_cmd
    {
      get { return _where_cmd; }
      set { _where_cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
