//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CFFormUnevenPrescribeLayDRG0120Info")]
  public partial class CFFormUnevenPrescribeLayDRG0120Info : global::ProtoBuf.IExtensible
  {
    public CFFormUnevenPrescribeLayDRG0120Info() {}
    
    private string _bogyong_code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bogyong_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_code
    {
      get { return _bogyong_code; }
      set { _bogyong_code = value; }
    }
    private string _bogyong_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bogyong_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_name
    {
      get { return _bogyong_name; }
      set { _bogyong_name = value; }
    }
    private string _pattern = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pattern", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pattern
    {
      get { return _pattern; }
      set { _pattern = value; }
    }
    private string _bogyong_gubun = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bogyong_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_gubun
    {
      get { return _bogyong_gubun; }
      set { _bogyong_gubun = value; }
    }
    private string _bogyong_jo_flag = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bogyong_jo_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_jo_flag
    {
      get { return _bogyong_jo_flag; }
      set { _bogyong_jo_flag = value; }
    }
    private string _bogyong_ju_flag = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"bogyong_ju_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_ju_flag
    {
      get { return _bogyong_ju_flag; }
      set { _bogyong_ju_flag = value; }
    }
    private string _bogyong_seok_flag = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"bogyong_seok_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_seok_flag
    {
      get { return _bogyong_seok_flag; }
      set { _bogyong_seok_flag = value; }
    }
    private string _bogyong_time1_flag = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"bogyong_time1_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_time1_flag
    {
      get { return _bogyong_time1_flag; }
      set { _bogyong_time1_flag = value; }
    }
    private string _bogyong_time2_flag = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"bogyong_time2_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_time2_flag
    {
      get { return _bogyong_time2_flag; }
      set { _bogyong_time2_flag = value; }
    }
    private string _bogyong_time3_flag = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"bogyong_time3_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_time3_flag
    {
      get { return _bogyong_time3_flag; }
      set { _bogyong_time3_flag = value; }
    }
    private string _bogyong_time4_flag = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"bogyong_time4_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_time4_flag
    {
      get { return _bogyong_time4_flag; }
      set { _bogyong_time4_flag = value; }
    }
    private string _bogyong_time5_flag = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"bogyong_time5_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_time5_flag
    {
      get { return _bogyong_time5_flag; }
      set { _bogyong_time5_flag = value; }
    }
    private string _bogyong_time6_flag = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"bogyong_time6_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_time6_flag
    {
      get { return _bogyong_time6_flag; }
      set { _bogyong_time6_flag = value; }
    }
    private string _bogyong_time7_flag = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"bogyong_time7_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_time7_flag
    {
      get { return _bogyong_time7_flag; }
      set { _bogyong_time7_flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
