//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DupCheckCPLOrder1RequestInfo")]
  public partial class DupCheckCPLOrder1RequestInfo : global::ProtoBuf.IExtensible
  {
    public DupCheckCPLOrder1RequestInfo() {}
    
    private string _newHangmog_code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"newHangmog_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string newHangmog_code
    {
      get { return _newHangmog_code; }
      set { _newHangmog_code = value; }
    }
    private string _newSpecimen_code = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"newSpecimen_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string newSpecimen_code
    {
      get { return _newSpecimen_code; }
      set { _newSpecimen_code = value; }
    }
    private string _oldHangmog_code = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"oldHangmog_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string oldHangmog_code
    {
      get { return _oldHangmog_code; }
      set { _oldHangmog_code = value; }
    }
    private string _oldSpecimen_code = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"oldSpecimen_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string oldSpecimen_code
    {
      get { return _oldSpecimen_code; }
      set { _oldSpecimen_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
