//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FnCplLoadDupGrdHangmogInfo")]
  public partial class FnCplLoadDupGrdHangmogInfo : global::ProtoBuf.IExtensible
  {
    public FnCplLoadDupGrdHangmogInfo() {}
    
    private string _hangmog_code1 = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hangmog_code1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hangmog_code1
    {
      get { return _hangmog_code1; }
      set { _hangmog_code1 = value; }
    }
    private string _specimen_code1 = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"specimen_code1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specimen_code1
    {
      get { return _specimen_code1; }
      set { _specimen_code1 = value; }
    }
    private string _hangmog_code2 = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hangmog_code2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hangmog_code2
    {
      get { return _hangmog_code2; }
      set { _hangmog_code2 = value; }
    }
    private string _specimen_code2 = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"specimen_code2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specimen_code2
    {
      get { return _specimen_code2; }
      set { _specimen_code2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
