//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FnInpLoadJaewonIlsuInfo")]
  public partial class FnInpLoadJaewonIlsuInfo : global::ProtoBuf.IExtensible
  {
    public FnInpLoadJaewonIlsuInfo() {}
    
    private string _cp_code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cp_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cp_code
    {
      get { return _cp_code; }
      set { _cp_code = value; }
    }
    private string _app_date = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"app_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string app_date
    {
      get { return _app_date; }
      set { _app_date = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
