//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HILoadCodeNameInfo")]
  public partial class HILoadCodeNameInfo : global::ProtoBuf.IExtensible
  {
    public HILoadCodeNameInfo() {}
    
    private string _order_gubun_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"order_gubun_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_gubun_name
    {
      get { return _order_gubun_name; }
      set { _order_gubun_name = value; }
    }
    private string _specimen_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"specimen_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specimen_name
    {
      get { return _specimen_name; }
      set { _specimen_name = value; }
    }
    private string _jusa_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"jusa_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jusa_name
    {
      get { return _jusa_name; }
      set { _jusa_name = value; }
    }
    private string _pay_name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pay_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pay_name
    {
      get { return _pay_name; }
      set { _pay_name = value; }
    }
    private string _bogyong_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bogyong_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_name
    {
      get { return _bogyong_name; }
      set { _bogyong_name = value; }
    }
    private string _jundal_part_out_name = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"jundal_part_out_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jundal_part_out_name
    {
      get { return _jundal_part_out_name; }
      set { _jundal_part_out_name = value; }
    }
    private string _jundal_part_inp_name = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"jundal_part_inp_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jundal_part_inp_name
    {
      get { return _jundal_part_inp_name; }
      set { _jundal_part_inp_name = value; }
    }
    private string _ord_danui_name = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ord_danui_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ord_danui_name
    {
      get { return _ord_danui_name; }
      set { _ord_danui_name = value; }
    }
    private string _mayak_yn = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"mayak_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mayak_yn
    {
      get { return _mayak_yn; }
      set { _mayak_yn = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
