//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HIOcsCheckJundalPartLoadJaeryoJundalInfo")]
  public partial class HIOcsCheckJundalPartLoadJaeryoJundalInfo : global::ProtoBuf.IExtensible
  {
    public HIOcsCheckJundalPartLoadJaeryoJundalInfo() {}
    
    private string _check_jundal = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"check_jundal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string check_jundal
    {
      get { return _check_jundal; }
      set { _check_jundal = value; }
    }
    private string _load_jaeryo_jundal = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"load_jaeryo_jundal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string load_jaeryo_jundal
    {
      get { return _load_jaeryo_jundal; }
      set { _load_jaeryo_jundal = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
