//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HIOcsSpecificCommentInfo")]
  public partial class HIOcsSpecificCommentInfo : global::ProtoBuf.IExtensible
  {
    public HIOcsSpecificCommentInfo() {}
    
    private string _specific_comment_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"specific_comment_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specific_comment_name
    {
      get { return _specific_comment_name; }
      set { _specific_comment_name = value; }
    }
    private string _specific_comment_sys_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"specific_comment_sys_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specific_comment_sys_id
    {
      get { return _specific_comment_sys_id; }
      set { _specific_comment_sys_id = value; }
    }
    private string _specific_comment_pgm_id = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"specific_comment_pgm_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specific_comment_pgm_id
    {
      get { return _specific_comment_pgm_id; }
      set { _specific_comment_pgm_id = value; }
    }
    private string _specific_comment_not_null = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"specific_comment_not_null", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specific_comment_not_null
    {
      get { return _specific_comment_not_null; }
      set { _specific_comment_not_null = value; }
    }
    private string _specific_comment_table_id = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"specific_comment_table_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specific_comment_table_id
    {
      get { return _specific_comment_table_id; }
      set { _specific_comment_table_id = value; }
    }
    private string _specific_comment_col_id = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"specific_comment_col_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specific_comment_col_id
    {
      get { return _specific_comment_col_id; }
      set { _specific_comment_col_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
