//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadHangmogInfo")]
  public partial class LoadHangmogInfo : global::ProtoBuf.IExtensible
  {
    public LoadHangmogInfo() {}
    
    private string _hangmog_code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hangmog_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hangmog_code
    {
      get { return _hangmog_code; }
      set { _hangmog_code = value; }
    }
    private string _hangmog_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hangmog_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hangmog_name
    {
      get { return _hangmog_name; }
      set { _hangmog_name = value; }
    }
    private string _slip_code = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"slip_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string slip_code
    {
      get { return _slip_code; }
      set { _slip_code = value; }
    }
    private string _group_yn = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"group_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string group_yn
    {
      get { return _group_yn; }
      set { _group_yn = value; }
    }
    private string _input_tab = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"input_tab", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string input_tab
    {
      get { return _input_tab; }
      set { _input_tab = value; }
    }
    private string _order_gubun = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"order_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_gubun
    {
      get { return _order_gubun; }
      set { _order_gubun = value; }
    }
    private string _input_control = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"input_control", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string input_control
    {
      get { return _input_control; }
      set { _input_control = value; }
    }
    private string _jundal_table_out = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"jundal_table_out", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jundal_table_out
    {
      get { return _jundal_table_out; }
      set { _jundal_table_out = value; }
    }
    private string _jundal_table_inp = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"jundal_table_inp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jundal_table_inp
    {
      get { return _jundal_table_inp; }
      set { _jundal_table_inp = value; }
    }
    private string _jundal_part_out = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"jundal_part_out", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jundal_part_out
    {
      get { return _jundal_part_out; }
      set { _jundal_part_out = value; }
    }
    private string _jundal_part_inp = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"jundal_part_inp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jundal_part_inp
    {
      get { return _jundal_part_inp; }
      set { _jundal_part_inp = value; }
    }
    private string _jaeryo_jundal_yn_out = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"jaeryo_jundal_yn_out", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jaeryo_jundal_yn_out
    {
      get { return _jaeryo_jundal_yn_out; }
      set { _jaeryo_jundal_yn_out = value; }
    }
    private string _jaeryo_jundal_yn_inp = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"jaeryo_jundal_yn_inp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jaeryo_jundal_yn_inp
    {
      get { return _jaeryo_jundal_yn_inp; }
      set { _jaeryo_jundal_yn_inp = value; }
    }
    private string _move_part = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"move_part", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string move_part
    {
      get { return _move_part; }
      set { _move_part = value; }
    }
    private string _suryang = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"suryang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string suryang
    {
      get { return _suryang; }
      set { _suryang = value; }
    }
    private string _ord_danui = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"ord_danui", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ord_danui
    {
      get { return _ord_danui; }
      set { _ord_danui = value; }
    }
    private string _dv_time = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"dv_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv_time
    {
      get { return _dv_time; }
      set { _dv_time = value; }
    }
    private string _dv = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"dv", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv
    {
      get { return _dv; }
      set { _dv = value; }
    }
    private string _jusa = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"jusa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jusa
    {
      get { return _jusa; }
      set { _jusa = value; }
    }
    private string _bogyong_code = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"bogyong_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_code
    {
      get { return _bogyong_code; }
      set { _bogyong_code = value; }
    }
    private string _suga_yn = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"suga_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string suga_yn
    {
      get { return _suga_yn; }
      set { _suga_yn = value; }
    }
    private string _sg_code = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"sg_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sg_code
    {
      get { return _sg_code; }
      set { _sg_code = value; }
    }
    private string _jaeryo_yn = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"jaeryo_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jaeryo_yn
    {
      get { return _jaeryo_yn; }
      set { _jaeryo_yn = value; }
    }
    private string _jaeryo_code = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"jaeryo_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jaeryo_code
    {
      get { return _jaeryo_code; }
      set { _jaeryo_code = value; }
    }
    private string _bulyong_ymd = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"bulyong_ymd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bulyong_ymd
    {
      get { return _bulyong_ymd; }
      set { _bulyong_ymd = value; }
    }
    private string _bulyong_check = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"bulyong_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bulyong_check
    {
      get { return _bulyong_check; }
      set { _bulyong_check = value; }
    }
    private string _bulyong_check_out = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"bulyong_check_out", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bulyong_check_out
    {
      get { return _bulyong_check_out; }
      set { _bulyong_check_out = value; }
    }
    private string _specimen_yn = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"specimen_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specimen_yn
    {
      get { return _specimen_yn; }
      set { _specimen_yn = value; }
    }
    private string _specimen_default = "";
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"specimen_default", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specimen_default
    {
      get { return _specimen_default; }
      set { _specimen_default = value; }
    }
    private string _portable_yn = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"portable_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string portable_yn
    {
      get { return _portable_yn; }
      set { _portable_yn = value; }
    }
    private string _portable_check = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"portable_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string portable_check
    {
      get { return _portable_check; }
      set { _portable_check = value; }
    }
    private string _xray_buwi = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"xray_buwi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string xray_buwi
    {
      get { return _xray_buwi; }
      set { _xray_buwi = value; }
    }
    private string _reser_yn_out = "";
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"reser_yn_out", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reser_yn_out
    {
      get { return _reser_yn_out; }
      set { _reser_yn_out = value; }
    }
    private string _reser_yn_inp = "";
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"reser_yn_inp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reser_yn_inp
    {
      get { return _reser_yn_inp; }
      set { _reser_yn_inp = value; }
    }
    private string _emergency = "";
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"emergency", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string emergency
    {
      get { return _emergency; }
      set { _emergency = value; }
    }
    private string _emergency_check = "";
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"emergency_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string emergency_check
    {
      get { return _emergency_check; }
      set { _emergency_check = value; }
    }
    private string _bom_yn = "";
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"bom_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bom_yn
    {
      get { return _bom_yn; }
      set { _bom_yn = value; }
    }
    private string _bichi_yn = "";
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"bichi_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bichi_yn
    {
      get { return _bichi_yn; }
      set { _bichi_yn = value; }
    }
    private string _wonyoi_order_yn = "";
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"wonyoi_order_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wonyoi_order_yn
    {
      get { return _wonyoi_order_yn; }
      set { _wonyoi_order_yn = value; }
    }
    private string _wonyoi_check = "";
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"wonyoi_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wonyoi_check
    {
      get { return _wonyoi_check; }
      set { _wonyoi_check = value; }
    }
    private string _powder_yn = "";
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"powder_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string powder_yn
    {
      get { return _powder_yn; }
      set { _powder_yn = value; }
    }
    private string _powder_check = "";
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"powder_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string powder_check
    {
      get { return _powder_check; }
      set { _powder_check = value; }
    }
    private string _nday_yn = "";
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"nday_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nday_yn
    {
      get { return _nday_yn; }
      set { _nday_yn = value; }
    }
    private string _chisik_yn = "";
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"chisik_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chisik_yn
    {
      get { return _chisik_yn; }
      set { _chisik_yn = value; }
    }
    private string _muhyo_yn = "";
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"muhyo_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string muhyo_yn
    {
      get { return _muhyo_yn; }
      set { _muhyo_yn = value; }
    }
    private string _nurse_input_yn = "";
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"nurse_input_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nurse_input_yn
    {
      get { return _nurse_input_yn; }
      set { _nurse_input_yn = value; }
    }
    private string _supply_input_yn = "";
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"supply_input_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string supply_input_yn
    {
      get { return _supply_input_yn; }
      set { _supply_input_yn = value; }
    }
    private string _limit_suryang = "";
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"limit_suryang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string limit_suryang
    {
      get { return _limit_suryang; }
      set { _limit_suryang = value; }
    }
    private string _limit_nalsu = "";
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"limit_nalsu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string limit_nalsu
    {
      get { return _limit_nalsu; }
      set { _limit_nalsu = value; }
    }
    private string _remark = "";
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"remark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string remark
    {
      get { return _remark; }
      set { _remark = value; }
    }
    private string _nurse_confirm_gubun = "";
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"nurse_confirm_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nurse_confirm_gubun
    {
      get { return _nurse_confirm_gubun; }
      set { _nurse_confirm_gubun = value; }
    }
    private string _specific_comment = "";
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"specific_comment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specific_comment
    {
      get { return _specific_comment; }
      set { _specific_comment = value; }
    }
    private string _hubal_change_check = "";
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"hubal_change_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hubal_change_check
    {
      get { return _hubal_change_check; }
      set { _hubal_change_check = value; }
    }
    private string _pharmacy_check = "";
    [global::ProtoBuf.ProtoMember(54, IsRequired = false, Name=@"pharmacy_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pharmacy_check
    {
      get { return _pharmacy_check; }
      set { _pharmacy_check = value; }
    }
    private string _drg_pack_check = "";
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"drg_pack_check", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string drg_pack_check
    {
      get { return _drg_pack_check; }
      set { _drg_pack_check = value; }
    }
    private string _dummy = "";
    [global::ProtoBuf.ProtoMember(56, IsRequired = false, Name=@"dummy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dummy
    {
      get { return _dummy; }
      set { _dummy = value; }
    }
    private string _dummy1 = "";
    [global::ProtoBuf.ProtoMember(57, IsRequired = false, Name=@"dummy1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dummy1
    {
      get { return _dummy1; }
      set { _dummy1 = value; }
    }
    private string _dummy2 = "";
    [global::ProtoBuf.ProtoMember(58, IsRequired = false, Name=@"dummy2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dummy2
    {
      get { return _dummy2; }
      set { _dummy2 = value; }
    }
    private string _dummy3 = "";
    [global::ProtoBuf.ProtoMember(59, IsRequired = false, Name=@"dummy3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dummy3
    {
      get { return _dummy3; }
      set { _dummy3 = value; }
    }
    private string _dummy4 = "";
    [global::ProtoBuf.ProtoMember(60, IsRequired = false, Name=@"dummy4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dummy4
    {
      get { return _dummy4; }
      set { _dummy4 = value; }
    }
    private string _dummy5 = "";
    [global::ProtoBuf.ProtoMember(61, IsRequired = false, Name=@"dummy5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dummy5
    {
      get { return _dummy5; }
      set { _dummy5 = value; }
    }
    private string _dummy6 = "";
    [global::ProtoBuf.ProtoMember(62, IsRequired = false, Name=@"dummy6", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dummy6
    {
      get { return _dummy6; }
      set { _dummy6 = value; }
    }
    private string _dummy7 = "";
    [global::ProtoBuf.ProtoMember(63, IsRequired = false, Name=@"dummy7", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dummy7
    {
      get { return _dummy7; }
      set { _dummy7 = value; }
    }
    private string _dummy8 = "";
    [global::ProtoBuf.ProtoMember(64, IsRequired = false, Name=@"dummy8", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dummy8
    {
      get { return _dummy8; }
      set { _dummy8 = value; }
    }
    private string _dummy9 = "";
    [global::ProtoBuf.ProtoMember(65, IsRequired = false, Name=@"dummy9", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dummy9
    {
      get { return _dummy9; }
      set { _dummy9 = value; }
    }
    private string _flag = "";
    [global::ProtoBuf.ProtoMember(66, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private string _msg = "";
    [global::ProtoBuf.ProtoMember(67, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
