//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model.proto
namespace IHIS.CloudConnector.Messaging
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadPatientNaewonListInfo")]
  public partial class LoadPatientNaewonListInfo : global::ProtoBuf.IExtensible
  {
    public LoadPatientNaewonListInfo() {}
    
    private string _ioe_gubun = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ioe_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ioe_gubun
    {
      get { return _ioe_gubun; }
      set { _ioe_gubun = value; }
    }
    private string _data_gubun = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data_gubun
    {
      get { return _data_gubun; }
      set { _data_gubun = value; }
    }
    private string _bunho = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bunho", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bunho
    {
      get { return _bunho; }
      set { _bunho = value; }
    }
    private string _naewon_date = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"naewon_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string naewon_date
    {
      get { return _naewon_date; }
      set { _naewon_date = value; }
    }
    private string _gwa = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gwa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gwa
    {
      get { return _gwa; }
      set { _gwa = value; }
    }
    private string _doctor = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"doctor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doctor
    {
      get { return _doctor; }
      set { _doctor = value; }
    }
    private string _doctor_name = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"doctor_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doctor_name
    {
      get { return _doctor_name; }
      set { _doctor_name = value; }
    }
    private string _naewon_type = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"naewon_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string naewon_type
    {
      get { return _naewon_type; }
      set { _naewon_type = value; }
    }
    private string _jubsu_no = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"jubsu_no", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jubsu_no
    {
      get { return _jubsu_no; }
      set { _jubsu_no = value; }
    }
    private string _jinryo_time = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"jinryo_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jinryo_time
    {
      get { return _jinryo_time; }
      set { _jinryo_time = value; }
    }
    private string _pk_key = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"pk_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pk_key
    {
      get { return _pk_key; }
      set { _pk_key = value; }
    }
    private string _reser_data_yn = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"reser_data_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reser_data_yn
    {
      get { return _reser_data_yn; }
      set { _reser_data_yn = value; }
    }
    private string _gubun = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gubun
    {
      get { return _gubun; }
      set { _gubun = value; }
    }
    private string _gubun_name = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"gubun_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gubun_name
    {
      get { return _gubun_name; }
      set { _gubun_name = value; }
    }
    private string _chojae = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"chojae", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chojae
    {
      get { return _chojae; }
      set { _chojae = value; }
    }
    private string _chojae_name = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"chojae_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chojae_name
    {
      get { return _chojae_name; }
      set { _chojae_name = value; }
    }
    private string _special_yn = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"special_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string special_yn
    {
      get { return _special_yn; }
      set { _special_yn = value; }
    }
    private string _naewon_yn = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"naewon_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string naewon_yn
    {
      get { return _naewon_yn; }
      set { _naewon_yn = value; }
    }
    private string _sunnab_yn = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"sunnab_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sunnab_yn
    {
      get { return _sunnab_yn; }
      set { _sunnab_yn = value; }
    }
    private string _ho_dong = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"ho_dong", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ho_dong
    {
      get { return _ho_dong; }
      set { _ho_dong = value; }
    }
    private string _ho_code = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"ho_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ho_code
    {
      get { return _ho_code; }
      set { _ho_code = value; }
    }
    private string _jaewon_flag = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"jaewon_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jaewon_flag
    {
      get { return _jaewon_flag; }
      set { _jaewon_flag = value; }
    }
    private string _ipwon_reser_yn = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"ipwon_reser_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ipwon_reser_yn
    {
      get { return _ipwon_reser_yn; }
      set { _ipwon_reser_yn = value; }
    }
    private string _real_naewon_yn = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"real_naewon_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string real_naewon_yn
    {
      get { return _real_naewon_yn; }
      set { _real_naewon_yn = value; }
    }
    private string _approve_doctor = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"approve_doctor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string approve_doctor
    {
      get { return _approve_doctor; }
      set { _approve_doctor = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}