//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadColumnCodeNameInfo")]
  public partial class LoadColumnCodeNameInfo : global::ProtoBuf.IExtensible
  {
    public LoadColumnCodeNameInfo() {}
    
    private string _col_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"col_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string col_name
    {
      get { return _col_name; }
      set { _col_name = value; }
    }
    private string _arg1 = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"arg1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string arg1
    {
      get { return _arg1; }
      set { _arg1 = value; }
    }
    private string _arg2 = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"arg2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string arg2
    {
      get { return _arg2; }
      set { _arg2 = value; }
    }
    private string _arg3 = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"arg3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string arg3
    {
      get { return _arg3; }
      set { _arg3 = value; }
    }
    private string _value = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
