//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model.proto
namespace IHIS.CloudConnector.Messaging
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadPatientBaseInfo")]
  public partial class LoadPatientBaseInfo : global::ProtoBuf.IExtensible
  {
    public LoadPatientBaseInfo() {}
    
    private string _io_suname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"io_suname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_suname
    {
      get { return _io_suname; }
      set { _io_suname = value; }
    }
    private string _io_suname2 = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"io_suname2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_suname2
    {
      get { return _io_suname2; }
      set { _io_suname2 = value; }
    }
    private string _io_sujumin1 = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"io_sujumin1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_sujumin1
    {
      get { return _io_sujumin1; }
      set { _io_sujumin1 = value; }
    }
    private string _io_sujumin2 = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"io_sujumin2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_sujumin2
    {
      get { return _io_sujumin2; }
      set { _io_sujumin2 = value; }
    }
    private string _io_sex = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"io_sex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_sex
    {
      get { return _io_sex; }
      set { _io_sex = value; }
    }
    private string _io_birth = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"io_birth", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_birth
    {
      get { return _io_birth; }
      set { _io_birth = value; }
    }
    private string _io_age = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"io_age", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_age
    {
      get { return _io_age; }
      set { _io_age = value; }
    }
    private string _io_age_num = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"io_age_num", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_age_num
    {
      get { return _io_age_num; }
      set { _io_age_num = value; }
    }
    private string _io_weight = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"io_weight", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_weight
    {
      get { return _io_weight; }
      set { _io_weight = value; }
    }
    private string _io_height = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"io_height", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_height
    {
      get { return _io_height; }
      set { _io_height = value; }
    }
    private string _io_zip_code1 = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"io_zip_code1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_zip_code1
    {
      get { return _io_zip_code1; }
      set { _io_zip_code1 = value; }
    }
    private string _io_zip_code2 = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"io_zip_code2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_zip_code2
    {
      get { return _io_zip_code2; }
      set { _io_zip_code2 = value; }
    }
    private string _io_address1 = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"io_address1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_address1
    {
      get { return _io_address1; }
      set { _io_address1 = value; }
    }
    private string _io_address2 = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"io_address2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_address2
    {
      get { return _io_address2; }
      set { _io_address2 = value; }
    }
    private string _io_tel = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"io_tel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_tel
    {
      get { return _io_tel; }
      set { _io_tel = value; }
    }
    private string _io_tel1 = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"io_tel1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_tel1
    {
      get { return _io_tel1; }
      set { _io_tel1 = value; }
    }
    private string _io_tel_hp = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"io_tel_hp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_tel_hp
    {
      get { return _io_tel_hp; }
      set { _io_tel_hp = value; }
    }
    private string _io_pace_maker_yn = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"io_pace_maker_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_pace_maker_yn
    {
      get { return _io_pace_maker_yn; }
      set { _io_pace_maker_yn = value; }
    }
    private string _io_dummy2 = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"io_dummy2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_dummy2
    {
      get { return _io_dummy2; }
      set { _io_dummy2 = value; }
    }
    private string _io_dummy3 = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"io_dummy3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_dummy3
    {
      get { return _io_dummy3; }
      set { _io_dummy3 = value; }
    }
    private string _io_flag = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"io_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string io_flag
    {
      get { return _io_flag; }
      set { _io_flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}