//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OBGetBogyongInfo")]
  public partial class OBGetBogyongInfo : global::ProtoBuf.IExtensible
  {
    public OBGetBogyongInfo() {}
    
    private string _bogyong_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bogyong_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_name
    {
      get { return _bogyong_name; }
      set { _bogyong_name = value; }
    }
    private string _nvl = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nvl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nvl
    {
      get { return _nvl; }
      set { _nvl = value; }
    }
    private string _donbog_yn = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"donbog_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string donbog_yn
    {
      get { return _donbog_yn; }
      set { _donbog_yn = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
