//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input.proto
// Note: requires additional types generated from: import.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OFUpdateOCS0303UpdateDataInfo")]
  public partial class OFUpdateOCS0303UpdateDataInfo : global::ProtoBuf.IExtensible
  {
    public OFUpdateOCS0303UpdateDataInfo() {}
    
    private string _group_ser = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"group_ser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string group_ser
    {
      get { return _group_ser; }
      set { _group_ser = value; }
    }
    private string _suryang = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"suryang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string suryang
    {
      get { return _suryang; }
      set { _suryang = value; }
    }
    private string _jusa = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"jusa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jusa
    {
      get { return _jusa; }
      set { _jusa = value; }
    }
    private string _pay = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pay
    {
      get { return _pay; }
      set { _pay = value; }
    }
    private string _dv_3 = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dv_3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv_3
    {
      get { return _dv_3; }
      set { _dv_3 = value; }
    }
    private string _order_gubun = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"order_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_gubun
    {
      get { return _order_gubun; }
      set { _order_gubun = value; }
    }
    private string _hubal_change_yn = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hubal_change_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hubal_change_yn
    {
      get { return _hubal_change_yn; }
      set { _hubal_change_yn = value; }
    }
    private string _hosp_code = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"hosp_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hosp_code
    {
      get { return _hosp_code; }
      set { _hosp_code = value; }
    }
    private string _nday_yn = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"nday_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nday_yn
    {
      get { return _nday_yn; }
      set { _nday_yn = value; }
    }
    private string _user_id = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _hangmog_code = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"hangmog_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hangmog_code
    {
      get { return _hangmog_code; }
      set { _hangmog_code = value; }
    }
    private string _ord_danui = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"ord_danui", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ord_danui
    {
      get { return _ord_danui; }
      set { _ord_danui = value; }
    }
    private string _bogyong_code = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"bogyong_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bogyong_code
    {
      get { return _bogyong_code; }
      set { _bogyong_code = value; }
    }
    private string _prn_yn = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"prn_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prn_yn
    {
      get { return _prn_yn; }
      set { _prn_yn = value; }
    }
    private string _dv_4 = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"dv_4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv_4
    {
      get { return _dv_4; }
      set { _dv_4 = value; }
    }
    private string _wonyoi_order_yn = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"wonyoi_order_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wonyoi_order_yn
    {
      get { return _wonyoi_order_yn; }
      set { _wonyoi_order_yn = value; }
    }
    private string _pharmacy = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"pharmacy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pharmacy
    {
      get { return _pharmacy; }
      set { _pharmacy = value; }
    }
    private string _memb_gubun = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"memb_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string memb_gubun
    {
      get { return _memb_gubun; }
      set { _memb_gubun = value; }
    }
    private string _fkocs0300_seq = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"fkocs0300_seq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fkocs0300_seq
    {
      get { return _fkocs0300_seq; }
      set { _fkocs0300_seq = value; }
    }
    private string _seq = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private string _dv_time = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"dv_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv_time
    {
      get { return _dv_time; }
      set { _dv_time = value; }
    }
    private string _emergency = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"emergency", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string emergency
    {
      get { return _emergency; }
      set { _emergency = value; }
    }
    private string _powder_yn = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"powder_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string powder_yn
    {
      get { return _powder_yn; }
      set { _powder_yn = value; }
    }
    private string _mix_group = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"mix_group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mix_group
    {
      get { return _mix_group; }
      set { _mix_group = value; }
    }
    private string _dangil_gumsa_order_yn = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"dangil_gumsa_order_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dangil_gumsa_order_yn
    {
      get { return _dangil_gumsa_order_yn; }
      set { _dangil_gumsa_order_yn = value; }
    }
    private string _jusa_spd_gubun = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"jusa_spd_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jusa_spd_gubun
    {
      get { return _jusa_spd_gubun; }
      set { _jusa_spd_gubun = value; }
    }
    private string _hangmog_name = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"hangmog_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hangmog_name
    {
      get { return _hangmog_name; }
      set { _hangmog_name = value; }
    }
    private string _memb = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"memb", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string memb
    {
      get { return _memb; }
      set { _memb = value; }
    }
    private string _pkocs0303 = "";
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"pkocs0303", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pkocs0303
    {
      get { return _pkocs0303; }
      set { _pkocs0303 = value; }
    }
    private string _dv = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"dv", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv
    {
      get { return _dv; }
      set { _dv = value; }
    }
    private string _muhyo = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"muhyo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string muhyo
    {
      get { return _muhyo; }
      set { _muhyo = value; }
    }
    private string _dv_1 = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"dv_1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv_1
    {
      get { return _dv_1; }
      set { _dv_1 = value; }
    }
    private string _order_remark = "";
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"order_remark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_remark
    {
      get { return _order_remark; }
      set { _order_remark = value; }
    }
    private string _dangil_gumsa_result_yn = "";
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"dangil_gumsa_result_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dangil_gumsa_result_yn
    {
      get { return _dangil_gumsa_result_yn; }
      set { _dangil_gumsa_result_yn = value; }
    }
    private string _drg_pack_yn = "";
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"drg_pack_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string drg_pack_yn
    {
      get { return _drg_pack_yn; }
      set { _drg_pack_yn = value; }
    }
    private string _amt = "";
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"amt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string amt
    {
      get { return _amt; }
      set { _amt = value; }
    }
    private string _yaksok_code = "";
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"yaksok_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string yaksok_code
    {
      get { return _yaksok_code; }
      set { _yaksok_code = value; }
    }
    private string _specimen_code = "";
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"specimen_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string specimen_code
    {
      get { return _specimen_code; }
      set { _specimen_code = value; }
    }
    private string _nalsu = "";
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"nalsu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nalsu
    {
      get { return _nalsu; }
      set { _nalsu = value; }
    }
    private string _portable_yn = "";
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"portable_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string portable_yn
    {
      get { return _portable_yn; }
      set { _portable_yn = value; }
    }
    private string _dv_2 = "";
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"dv_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dv_2
    {
      get { return _dv_2; }
      set { _dv_2 = value; }
    }
    private string _nurse_remark = "";
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"nurse_remark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nurse_remark
    {
      get { return _nurse_remark; }
      set { _nurse_remark = value; }
    }
    private string _input_tab = "";
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"input_tab", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string input_tab
    {
      get { return _input_tab; }
      set { _input_tab = value; }
    }
    private string _bom_source_key = "";
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"bom_source_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bom_source_key
    {
      get { return _bom_source_key; }
      set { _bom_source_key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
