//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrOcsLoadNaewonInfo")]
  public partial class PrOcsLoadNaewonInfo : global::ProtoBuf.IExtensible
  {
    public PrOcsLoadNaewonInfo() {}
    
    private string _chisik_yn = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chisik_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chisik_yn
    {
      get { return _chisik_yn; }
      set { _chisik_yn = value; }
    }
    private string _weight_input_yn = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"weight_input_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string weight_input_yn
    {
      get { return _weight_input_yn; }
      set { _weight_input_yn = value; }
    }
    private string _wonyoi_order_yn = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"wonyoi_order_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wonyoi_order_yn
    {
      get { return _wonyoi_order_yn; }
      set { _wonyoi_order_yn = value; }
    }
    private string _wonnae_sayu_code = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"wonnae_sayu_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wonnae_sayu_code
    {
      get { return _wonnae_sayu_code; }
      set { _wonnae_sayu_code = value; }
    }
    private string _wonnae_sayu_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"wonnae_sayu_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wonnae_sayu_name
    {
      get { return _wonnae_sayu_name; }
      set { _wonnae_sayu_name = value; }
    }
    private string _inp_bonin = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"inp_bonin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string inp_bonin
    {
      get { return _inp_bonin; }
      set { _inp_bonin = value; }
    }
    private string _sabun = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sabun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sabun
    {
      get { return _sabun; }
      set { _sabun = value; }
    }
    private string _sabun_name = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sabun_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sabun_name
    {
      get { return _sabun_name; }
      set { _sabun_name = value; }
    }
    private string _ga_jubsu_gubun = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"ga_jubsu_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ga_jubsu_gubun
    {
      get { return _ga_jubsu_gubun; }
      set { _ga_jubsu_gubun = value; }
    }
    private string _out_toiwon_yn = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"out_toiwon_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string out_toiwon_yn
    {
      get { return _out_toiwon_yn; }
      set { _out_toiwon_yn = value; }
    }
    private string _drg_nalsu = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"drg_nalsu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string drg_nalsu
    {
      get { return _drg_nalsu; }
      set { _drg_nalsu = value; }
    }
    private string _jinryo_result = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"jinryo_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jinryo_result
    {
      get { return _jinryo_result; }
      set { _jinryo_result = value; }
    }
    private string _soa_nutjido_yn = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"soa_nutjido_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string soa_nutjido_yn
    {
      get { return _soa_nutjido_yn; }
      set { _soa_nutjido_yn = value; }
    }
    private string _atc_yn = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"atc_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string atc_yn
    {
      get { return _atc_yn; }
      set { _atc_yn = value; }
    }
    private string _sunnab_yn = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"sunnab_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sunnab_yn
    {
      get { return _sunnab_yn; }
      set { _sunnab_yn = value; }
    }
    private string _hubal_change_yn = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"hubal_change_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hubal_change_yn
    {
      get { return _hubal_change_yn; }
      set { _hubal_change_yn = value; }
    }
    private string _next_jinryo_yn = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"next_jinryo_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string next_jinryo_yn
    {
      get { return _next_jinryo_yn; }
      set { _next_jinryo_yn = value; }
    }
    private string _dangil_gumsa_yn = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"dangil_gumsa_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dangil_gumsa_yn
    {
      get { return _dangil_gumsa_yn; }
      set { _dangil_gumsa_yn = value; }
    }
    private string _flag = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
