//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrOcsLoadIpwonInfo")]
  public partial class PrOcsLoadIpwonInfo : global::ProtoBuf.IExtensible
  {
    public PrOcsLoadIpwonInfo() {}
    
    private string _chisik_yn = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chisik_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chisik_yn
    {
      get { return _chisik_yn; }
      set { _chisik_yn = value; }
    }
    private string _weight_input_yn = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"weight_input_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string weight_input_yn
    {
      get { return _weight_input_yn; }
      set { _weight_input_yn = value; }
    }
    private string _wonyoi_order_yn = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"wonyoi_order_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wonyoi_order_yn
    {
      get { return _wonyoi_order_yn; }
      set { _wonyoi_order_yn = value; }
    }
    private string _wonnae_sayu_code = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"wonnae_sayu_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wonnae_sayu_code
    {
      get { return _wonnae_sayu_code; }
      set { _wonnae_sayu_code = value; }
    }
    private string _wonnae_sayu_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"wonnae_sayu_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wonnae_sayu_name
    {
      get { return _wonnae_sayu_name; }
      set { _wonnae_sayu_name = value; }
    }
    private string _cht_ipwon_date = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"cht_ipwon_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cht_ipwon_date
    {
      get { return _cht_ipwon_date; }
      set { _cht_ipwon_date = value; }
    }
    private string _double_ipwon_type = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"double_ipwon_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string double_ipwon_type
    {
      get { return _double_ipwon_type; }
      set { _double_ipwon_type = value; }
    }
    private string _ipwon_gwa = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ipwon_gwa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ipwon_gwa
    {
      get { return _ipwon_gwa; }
      set { _ipwon_gwa = value; }
    }
    private string _parent_gwa = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"parent_gwa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string parent_gwa
    {
      get { return _parent_gwa; }
      set { _parent_gwa = value; }
    }
    private string _resident = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"resident", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resident
    {
      get { return _resident; }
      set { _resident = value; }
    }
    private string _resident_name = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"resident_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resident_name
    {
      get { return _resident_name; }
      set { _resident_name = value; }
    }
    private string _drg_yn = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"drg_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string drg_yn
    {
      get { return _drg_yn; }
      set { _drg_yn = value; }
    }
    private string _drg_no = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"drg_no", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string drg_no
    {
      get { return _drg_no; }
      set { _drg_no = value; }
    }
    private string _inp_double_ipwon_type = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"inp_double_ipwon_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string inp_double_ipwon_type
    {
      get { return _inp_double_ipwon_type; }
      set { _inp_double_ipwon_type = value; }
    }
    private string _toiwon_goji_yn = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"toiwon_goji_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string toiwon_goji_yn
    {
      get { return _toiwon_goji_yn; }
      set { _toiwon_goji_yn = value; }
    }
    private string _toiwon_date = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"toiwon_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string toiwon_date
    {
      get { return _toiwon_date; }
      set { _toiwon_date = value; }
    }
    private string _incu_yn = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"incu_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string incu_yn
    {
      get { return _incu_yn; }
      set { _incu_yn = value; }
    }
    private string _jinryo_result = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"jinryo_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jinryo_result
    {
      get { return _jinryo_result; }
      set { _jinryo_result = value; }
    }
    private string _ga_toiwon_date = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"ga_toiwon_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ga_toiwon_date
    {
      get { return _ga_toiwon_date; }
      set { _ga_toiwon_date = value; }
    }
    private string _simsa_magam_yn = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"simsa_magam_yn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string simsa_magam_yn
    {
      get { return _simsa_magam_yn; }
      set { _simsa_magam_yn = value; }
    }
    private string _toiwon_res_date = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"toiwon_res_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string toiwon_res_date
    {
      get { return _toiwon_res_date; }
      set { _toiwon_res_date = value; }
    }
    private string _flag = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
