//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: model.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrOcsLoadIpwonReserInfo")]
  public partial class PrOcsLoadIpwonReserInfo : global::ProtoBuf.IExtensible
  {
    public PrOcsLoadIpwonReserInfo() {}
    
    private string _ipwon_gwa = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ipwon_gwa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ipwon_gwa
    {
      get { return _ipwon_gwa; }
      set { _ipwon_gwa = value; }
    }
    private string _parent_gwa = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"parent_gwa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string parent_gwa
    {
      get { return _parent_gwa; }
      set { _parent_gwa = value; }
    }
    private string _resident = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"resident", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resident
    {
      get { return _resident; }
      set { _resident = value; }
    }
    private string _flag = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
