//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sample.proto
namespace IHIS.CloudConnector.Messaging
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SaveOfenUsedHangmogInfo")]
  public partial class SaveOfenUsedHangmogInfo : global::ProtoBuf.IExtensible
  {
    public SaveOfenUsedHangmogInfo() {}
    
    private string _IUD_gubun = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IUD_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IUD_gubun
    {
      get { return _IUD_gubun; }
      set { _IUD_gubun = value; }
    }
    private string _memb_gubun = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"memb_gubun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string memb_gubun
    {
      get { return _memb_gubun; }
      set { _memb_gubun = value; }
    }
    private string _memb = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"memb", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string memb
    {
      get { return _memb; }
      set { _memb = value; }
    }
    private string _hangmog_code = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hangmog_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hangmog_code
    {
      get { return _hangmog_code; }
      set { _hangmog_code = value; }
    }
    private string _seq = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private string _often_use = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"often_use", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string often_use
    {
      get { return _often_use; }
      set { _often_use = value; }
    }
    private string _user_info = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"user_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_info
    {
      get { return _user_info; }
      set { _user_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
